### ISSUE TITLE
feature request track local apks and list updates to installed apps

### ISSUE THREAD

**Issue by nutpantz** [dkanada/OpenAPK#1]
track local apks and list updates to installed apps
I always have a number of apks on my multiple devices.
(I primarily use one or two devices to get updates then transfer apks to other devices)
Some times I have the latest installed other times I have forgotten
It would be great if your app could monitor a directory(and it's sub directories)
For apks that are never than installed
Maybe even some way to delete older version apks than installed.

**Comment by dkanada** [comment]
I am not entirely sure if this is within the scope of the app but I will look into it. If I do include this feature it will be after the 1.0 release, my main goal for the next update will be to improve the app list refresh so that it works in the background and doesn't reset the lists when it completes.

**Comment by dkanada** [comment]
I don't think I will be adding this, it would take a while to implement and I would rather work on other features like backups and moving apps to the system partition.
