### ISSUE TITLE
Bug: Disabled System Apps still appear in "System Apps"

### ISSUE THREAD

**Issue by jw243** [dkanada/OpenAPK#4]
Whenever an app is hidden, it appears in "hidden apps" and is removed from "system apps". However, when an app is disabled, it appears in " disabled apps" but at the same time remains in "system apps". 

As a result, it is very difficult to distinguish between disabled and active apps in "system apps".

By the way, I cannot find a difference in behaviour between a disabled and hidden app. In both cases, the apps disappear from the app drawer and do not function anymore.

**Comment by dkanada** [comment]
This will be fixed in the next update. I am transitioning over to a database for the app lists that will make things much easier moving forward. I think individual services or activities can be disabled whereas hiding only works on the entire application, that might be a nice feature. Also, hiding might work without root access, I still have to look into this.

Here is the [thread](http://android.stackexchange.com/questions/128949/pm-hide-vs-pm-disable-the-identity-crisis) that I had read a while ago about the differences. I have been testing out the commands today and I don't think hide works without root anymore. However, it does look like disable removes the app from the system settings whereas hide does not. I think I will leave both commands for now. Also, something to note is that when the 1.0 update happens the app will probably need to be reinstalled, the old code for appLists is not compatible with the database.

EDIT: It looks like disabled apps will still show up with searches in the package manager but will not show up in the system settings while hidden apps will have the opposite behavior. I will add new information about the two states to this comment.

**Comment by dkanada** [comment]
Here is the [thread](http://android.stackexchange.com/questions/128949/pm-hide-vs-pm-disable-the-identity-crisis) that I had read a while ago about the differences. I have been testing out the commands today and I don't think hide works without root anymore. However, it does look like disable removes the app from the system settings whereas hide does not. I think I will leave both commands for now. Also, something to note is that when the 1.0 update happens the app will probably need to be reinstalled, the old code for appLists is not compatible with the database.

**Comment by dkanada** [comment]
It looks like disabled apps will still show up with searches in the package manager but will not show up in system settings while hidden apps will have the opposite behavior. I will add new information about the two states to this comment.
