### ISSUE TITLE
Sorting won't work after update 0.9 -> 1.0

### ISSUE THREAD

**Issue by TheDcoder** [dkanada/OpenAPK#5]
Hello, the sorting won't work after I updated to 1.0 😞

Only the "Name" sort works, the rest of them don't. I have set the sort option to "Installation Data" and not it isn't working!

I hope this get fixed in the next release 😄

**Comment by dkanada** [comment]
I hadn't noticed that, thanks. It will be working after the 1.0.2 update. It looks like the first two sort methods work, only the installation date and last update are currently broken.

**Comment by TheDcoder** [comment]
Ah, ok. Thanks for the update! 😄

**Comment by dkanada** [comment]
I have fixed the issue breaking the sort by install time and last update, it should be updated on F-Droid soon. Sorting by size is still broken, it looks like it was never working in the first place. I will hopefully implement size in the next release or two. It might have to be root only because Android doesn't allow apps to get the size from a method call.

**Comment by TheDcoder** [comment]
Great! Thanks for fixing the issue! 😄
